version: "3.9"
services:
  api:
    container_name: routing-api-container
    build: .
    image: routing-api
    restart: always
    volumes:
      - ./package.json:/usr/app/routing-api/package.json
    command: bash -c "npm install --omit=dev && npm start"
    ports:
      - "5050:5050"